# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autobots < Formula
  desc "A CLI to create Microservices Mono structure for Go, Python frameworks"
  homepage ""
  version "1.0.5"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gochronicles/gc-cli/releases/download/v1.0.5/autobots_1.0.5_macOS_x86_64.tar.gz"
      sha256 "baa7e6ac669cf498e2cd1d4b95eacdd2c03aeba351362849567a790fb35fa540"
    end
    if Hardware::CPU.arm?
      url "https://github.com/gochronicles/gc-cli/releases/download/v1.0.5/autobots_1.0.5_macOS_arm64.tar.gz"
      sha256 "5efd2595355515d68c4d5cfd9291312403e88747bef5ec7d359df5589827e250"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gochronicles/gc-cli/releases/download/v1.0.5/autobots_1.0.5_Linux_x86_64.tar.gz"
      sha256 "fae01bb79ef19fe454c4cb0ec1ae149797947cf2081ce1f02675ad99028e9fa6"
    end
  end

  depends_on "git"
  depends_on "go"

  def install
    bin.install "autobots"
  end

  def caveats; <<~EOS
    A CLI to create Microservices Mono structure for Go, Python frameworks. Use autobots roll to create
  EOS
  end
end
