# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autobots < Formula
  desc "A CLI to create Microservices Mono structure for Go, Python frameworks"
  homepage "https://github.com/gochronicles/cli"
  version "1.0.1"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gochronicles/cli/releases/download/v1.0.1/autobots_1.0.1_macOS_x86_64.tar.gz"
      sha256 "11326fba6e8f59a5d84c0a25ed3700fb8c6f77df40bb8cd424562170e82bb954"
    end
    if Hardware::CPU.arm?
      url "https://github.com/gochronicles/cli/releases/download/v1.0.1/autobots_1.0.1_macOS_arm64.tar.gz"
      sha256 "741565a6836c9fa4918d6d5e1d15fd2d4195eeaf5e813e21d3fb88a1526062bb"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gochronicles/cli/releases/download/v1.0.1/autobots_1.0.1_Linux_x86_64.tar.gz"
      sha256 "250fadd3aa7d2bcb6dff383242b841df3d66ae571108126de005c229c8794430"
    end
  end

  depends_on "git"
  depends_on "go"

  def install
    bin.install "autobots"
  end

  def caveats; <<~EOS
    A CLI to create Microservices Mono structure for Go, Python frameworks. Use autobots roll to create
  EOS
  end
end
