# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autobots < Formula
  desc "A CLI to create Microservices Mono structure for Go, Python frameworks"
  homepage "https://github.com/gochronicles/cli"
  version "1.0.6"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gochronicles/cli/releases/download/v1.0.6/autobots_1.0.6_macOS_x86_64.tar.gz"
      sha256 "fc8f148794fad7e4f22a524d2be887b23ec365633dfa6c31de5fe4a773358b08"
    end
    if Hardware::CPU.arm?
      url "https://github.com/gochronicles/cli/releases/download/v1.0.6/autobots_1.0.6_macOS_arm64.tar.gz"
      sha256 "cd63570ee9f9da92da5f5552db4ee9925d39e3d5807bf6158072032242e4d5b1"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gochronicles/cli/releases/download/v1.0.6/autobots_1.0.6_Linux_x86_64.tar.gz"
      sha256 "98cedb941946d332d43e831eb5dc16cf60b100fd6be638808fc32dcbe7556bae"
    end
  end

  depends_on "git"
  depends_on "go"

  def install
    bin.install "autobots"
  end

  def caveats; <<~EOS
    A CLI to create Microservices Mono structure for Go, Python frameworks. Use autobots roll to create
  EOS
  end
end
