# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autobots < Formula
  desc "A CLI to create Microservices Mono structure for Go, Python frameworks"
  homepage "https://github.com/gochronicles/cli"
  version "1.0.6"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gochronicles/cli/releases/download/v1.0.6/autobots_1.0.6_macOS_x86_64.tar.gz"
      sha256 "c7af172e2f2197a8c81153031fe1bf873995a940cf53acea9f2256b503f60687"
    end
    if Hardware::CPU.arm?
      url "https://github.com/gochronicles/cli/releases/download/v1.0.6/autobots_1.0.6_macOS_arm64.tar.gz"
      sha256 "de58c59fe25b2714c6e03d87f95897cf7531a781995e53a204c3c69226c6aa8f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gochronicles/cli/releases/download/v1.0.6/autobots_1.0.6_Linux_x86_64.tar.gz"
      sha256 "3a458fa716c943e27595513620199fa2bc61ef2ea4b773b18d2741d9260793f8"
    end
  end

  depends_on "git"
  depends_on "go"

  def install
    bin.install "autobots"
  end

  def caveats; <<~EOS
    A CLI to create Microservices Mono structure for Go, Python frameworks. Use autobots roll to create
  EOS
  end
end
